services:
  firefly:
    image: ghcr.io/forlornlawngnome/wled-fireflies:latest
    ports:
      - "5000:5000"
    restart: unless-stopped
    network_mode: host
    volumes:
      - firefly-data:/data

volumes:
  firefly-data:
